# Generated by Django 5.1.15 on 2026-10-02 15:06

import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.lookups
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'db_table': 'comments_comment',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(condition=models.Q(('parent__isnull', True)), fields=['post', 'created_at', 'id'], name='idx_comment_roots'), models.Index(condition=models.Q(('parent__isnull', False)), fields=['parent', 'created_at', 'id'], name='idx_comment_replies')],
                'constraints': [models.CheckConstraint(condition=models.Q(('parent', models.F('id')), _negated=True), name='ck_comment_not_self_parent'), models.CheckConstraint(condition=models.Q(models.Q(('deleted_at__isnull', False), ('is_deleted', True)), models.Q(('deleted_at__isnull', True), ('is_deleted', False)), _connector='OR'), name='ck_comment_deleted_state'), models.CheckConstraint(condition=models.Q(('is_deleted', True), django.db.models.lookups.GreaterThan(django.db.models.functions.text.Length(django.db.models.functions.text.Trim('body')), 0), _connector='OR'), name='ck_comment_not_blank_unless_deleted'), models.CheckConstraint(condition=django.db.models.lookups.LessThanOrEqual(django.db.models.functions.text.Length('body'), 2000), name='ck_comment_body_len')],
            },
        ),
    ]
