# Generated by Django 5.1.15 on 2026-10-02 08:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('display_name', models.CharField(blank=True, default='', max_length=80)),
                ('bio', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
                'db_table': 'accounts_profile',
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'email verification token',
                'verbose_name_plural': 'email verification tokens',
                'db_table': 'accounts_emailverificationtoken',
                'constraints': [models.UniqueConstraint(fields=('token_hash',), name='uq_email_verification_token_hash'), models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='ck_email_verification_expires_after_created')],
            },
        ),
        migrations.CreateModel(
            name='RefreshTokenRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('jti', models.UUIDField(db_index=True, unique=True)),
                ('family_id', models.UUIDField(db_index=True)),
                ('family_started_at', models.DateTimeField()),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.CharField(blank=True, choices=[('rotated', 'Rotated'), ('logout', 'Logout'), ('reuse_detected', 'Reuse Detected'), ('deactivated', 'Deactivated')], max_length=20, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='accounts.refreshtokenrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'refresh token record',
                'verbose_name_plural': 'refresh token records',
                'db_table': 'accounts_refreshtokenrecord',
                'indexes': [models.Index(fields=['family_id'], name='idx_refresh_token_family_id'), models.Index(fields=['user_id'], name='idx_refresh_token_user_id'), models.Index(fields=['expires_at'], name='idx_refresh_token_expires_at')],
                'constraints': [models.UniqueConstraint(fields=('jti',), name='uq_refresh_token_record_jti'), models.CheckConstraint(condition=models.Q(models.Q(('revoke_reason__isnull', True), ('revoked_at__isnull', True)), models.Q(('revoke_reason__isnull', False), ('revoked_at__isnull', False)), _connector='OR'), name='ck_refresh_token_revoked_reason_sync'), models.CheckConstraint(condition=models.Q(('revoke_reason__isnull', True), ('revoke_reason__in', ['rotated', 'logout', 'reuse_detected', 'deactivated']), _connector='OR'), name='ck_refresh_token_revoke_reason_choices')],
            },
        ),
    ]
