# Generated by Django 5.1.15 on 2026-10-03 05:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='blog.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'bookmark',
                'verbose_name_plural': 'bookmarks',
                'db_table': 'engagement_bookmark',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', '-created_at', '-id'], name='idx_bookmark_user_feed'), models.Index(fields=['post'], name='idx_bookmark_post')],
                'constraints': [models.UniqueConstraint(fields=('user', 'post'), name='uq_bookmark_user_post')],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'like',
                'verbose_name_plural': 'likes',
                'db_table': 'engagement_like',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['post'], name='idx_like_post')],
                'constraints': [models.UniqueConstraint(fields=('user', 'post'), name='uq_like_user_post')],
            },
        ),
    ]
