# Generated by Django 5.1.15 on 2026-10-02 13:23

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.lookups
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'blog_category',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uq_category_name_lower'), models.UniqueConstraint(fields=('slug',), name='uq_category_slug')],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('excerpt', models.CharField(blank=True, default='', max_length=300)),
                ('content_markdown', models.TextField(blank=True, default='')),
                ('content_text', models.TextField(blank=True, default='')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('like_count', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blog.category')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'db_table': 'blog_post',
                'indexes': [models.Index(condition=models.Q(('status', 'published')), fields=['-published_at', '-id'], name='idx_post_public_feed'), models.Index(condition=models.Q(('status', 'published')), fields=['category', '-published_at', '-id'], name='idx_post_category_public'), models.Index(fields=['author', 'status', '-created_at', '-id'], name='idx_post_author_status'), models.Index(condition=models.Q(('status', 'published')), fields=['-like_count', '-id'], name='idx_post_popular_public'), django.contrib.postgres.indexes.GinIndex(condition=models.Q(('status', 'published')), fields=['search_vector'], name='idx_post_search_gin')],
                'constraints': [models.UniqueConstraint(fields=('slug',), name='uq_post_slug'), models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'published'])), name='ck_post_status'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'published'), _negated=True), ('published_at__isnull', False), _connector='OR'), name='ck_post_published_has_timestamp'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'published'), _negated=True), django.db.models.lookups.GreaterThan(django.db.models.functions.text.Length(django.db.models.functions.text.Trim('content_markdown')), 0), _connector='OR'), name='ck_post_published_not_blank'), models.CheckConstraint(condition=models.Q(('like_count__gte', 0)), name='ck_post_like_count_nonneg'), models.CheckConstraint(condition=django.db.models.lookups.GreaterThanOrEqual(django.db.models.functions.text.Length('title'), 3), name='ck_post_title_len')],
            },
        ),
    ]
